run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

output:
  format: colored-line-number

linters:
  enable:
    - errorlint
    - errname
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
